version: '2'
services:
    ptemagic-app:
        image: ptemagic
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://ptemagic-postgresql:5432/PteMagic
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ptemagic-postgresql:
        extends:
            file: postgresql.yml
            service: ptemagic-postgresql
