version: '2'
services:
    ptemagic-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/PteMagic/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=PteMagic
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
